# Generated by Django 4.1.4 on 2024-01-28 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditcard_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='issued',
            field=models.DateField(default=datetime.date(2024, 1, 28), verbose_name='issued'),
        ),
    ]
