# Generated by Django 4.1.4 on 2024-03-24 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditcard_management', '0003_alter_creditcard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='issued',
            field=models.DateField(default=datetime.date(2024, 3, 24), verbose_name='issued'),
        ),
    ]
